### ISSUE TITLE
Remove support for macvtap with Firecracker

### ISSUE THREAD

**Issue by richardcase** [liquidmetal-dev/flintlock#856]
**Describe the solution you'd like:**
Currently we use a forked version of Firecracker to get macvtap support. However, this feature isn't merged into main of Firecracker yet and its painful to continue to support a forked version.

Proposal:
- Remove usage of Forked firecracker version
- Update supported features to say macvtap is only supported with cloud hypervisor

**Why do you want this feature:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by mmchougule** [comment]
@richardcase  Anyone working on this? If possible, I would like to work to clean up firecracker and macvtap support for cloud hypervisor.

**Comment by richardcase** [comment]
@mmchougule - there is no one working on this yet, so that would be great if you wanted to work on it.  I had a couple of thoughts on this that may help:

- We could introduce a new **capability** that a provider says if they support for macvtap.
  - Capabilities are defined [here](https://github.com/liquidmetal-dev/flintlock/blob/main/core/models/capability.go)
  -  The Firecracker & CloudHypervisor could publish whether they support macvtap (Firecracker doesn't but CH does). This is done using the [Capabilities](https://github.com/liquidmetal-dev/flintlock/blob/main/infrastructure/microvm/firecracker/provider.go#L58) function on the provider interface
  -  Somewhere in the [core](https://github.com/liquidmetal-dev/flintlock/tree/main/core) we'd need to check that an incoming microvm create request that the network interfaces if they have macvtap defined and if the provider doesn't support it then return an error
-  There is a [GHA workflow](https://github.com/liquidmetal-dev/flintlock/blob/main/.github/workflows/fork.yaml) that checks for new firecracker versions and create an issue to update the fork. This can be deleted as we won't support the fork going forward
  - Do you think it would be worth still checking for new Firecracker & Cloud Hypervisor releases and creating an issue for someone to check compatibility?
- Docs would need updating to remove mention of using the fork. 

Feel free to ping me if you have any questions. We've also created a slack channel in the CNCF slack.

**Comment by richardcase** [comment]
@mmchougule - just checking in to see if you wanted to work on this? On pressure, if you don't then i will pick it up.

**Comment by mmchougule** [comment]
ah sorry I completely missed the notification. Thanks for working on it. I will look into others.
